[Icon Theme]
Name=blueprint-WhiteSur-dark-GNOME
Comment=AlexOS custom blueprint icons with GNOME fallbacks
Inherits=Adwaita,hicolor
Directories=scalable/apps,scalable/places,scalable/categories,scalable/devices,scalable/status,scalable/mimetypes

[scalable/apps]
Size=128
MinSize=16
MaxSize=512
Type=Scalable
Context=Applications

[scalable/places]
Size=128
MinSize=16
MaxSize=512
Type=Scalable
Context=Places

[scalable/categories]
Size=128
MinSize=16
MaxSize=512
Type=Scalable
Context=Categories

[scalable/devices]
Size=128
MinSize=16
MaxSize=512
Type=Scalable
Context=Devices

[scalable/status]
Size=128
MinSize=16
MaxSize=512
Type=Scalable
Context=Status

[scalable/mimetypes]
Size=128
MinSize=16
MaxSize=512
Type=Scalable
Context=MimeTypes
