---
services:
  - name: "NetworkManager"
    mandatory: false
targets:
  - name: "graphical"
    mandatory: false
timers:
  - name: "alexos-update"
    mandatory: false
disable:
  - name: "alexos-first-boot"
    mandatory: false
disable-targets: []
mask: []
